name: CI workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:

  scan:

    runs-on: ubuntu-latest

    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Scan with Sonarqube
        uses: sonarsource/sonarqube-scan-action@master

